[package]
name = "metlang-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
structopt = "0.3"
thiserror = "1.0"
libbf = { version = "0.0", git = "https://github.com/yoh2/libbf-rs" }